-- CONSULTA COM OBJETIVO DE IDENTIFICAR O NOME DO CLIENTE DO GENERO MASCULINO QUE SEJA PAI E ORDENAR POR NOME.
SELECT NM_CLIENTE AS "Nome do cliente", DG_GENERO_CLIENTE AS "Gênero"
    FROM T_BR_CLIENTE
    WHERE DS_GRAUPARENTESCO_CLIENTE = 'PAI'
ORDER BY NM_CLIENTE ASC;

-- CONSULTA COM OBJETIVO DE IDENTIFICAR O AS EMPRESAS QUE UTILIZAM DE VANS  DE MARCA FIAT E DE COR VERMELHA.
SELECT E.NM_EMPRESA as "Nome empresa", A.NM_MARCA_AUTOMOVEL as "Marca", A.DS_COR_AUTOMOVEL AS "Cor", A.DS_PLACA_AUTOMOVEL AS "Placa"
    FROM T_BR_EMPRESA E LEFT OUTER JOIN T_BR_AUTOMOVEL A
    ON (E.CD_EMPRESA = A.CD_EMPRESA)
    WHERE A.NM_MARCA_AUTOMOVEL = 'FIAT';

-- CONSULTA COM OBJETIVO DE IDENTIFICAR AS MARCAS QUE CADA EMPRESA UTLIZA.
SELECT E.NM_EMPRESA AS "Nome empresa", A.NM_MARCA_AUTOMOVEL AS "Veículos"
    FROM T_BR_EMPRESA E LEFT OUTER JOIN T_BR_AUTOMOVEL A
    ON (E.CD_EMPRESA = A.CD_EMPRESA);

-- CONSULTA COM OBJETIVO DE IDENTIFICAR AS EMPRESAS QUE POSSUEM 1 VEÍCULO REGISTRADO E ORDENAR POR NOME DA EMPRESA
SELECT E.NM_EMPRESA AS "Nome empresa", COUNT(A.CD_AUTOMOVEL) AS "Quantidade de veiculo"
    FROM T_BR_EMPRESA E LEFT OUTER JOIN T_BR_AUTOMOVEL A
    ON (E.CD_EMPRESA = A.CD_EMPRESA)
    GROUP BY E.NM_EMPRESA
    HAVING COUNT(A.CD_AUTOMOVEL) = 1
ORDER BY E.NM_EMPRESA ASC;
    