-- NESSE SELECT QUEREMOS SABER A QUANTIDADE DE CLIENTES CADASTRADOS COM O SOBRENOME SILVA E ORDENAR PELO O NOME DOS CLIENTES.
SELECT NM_CLIENTE AS "Nome do cliente", NM_SOBRENOME_CLIENTE AS "Sobrenome do cliente"
    FROM T_HS_CLIENTE
    WHERE NM_SOBRENOME_CLIENTE = 'SILVA'
ORDER BY NM_CLIENTE ASC;

-- NO SELECT ABAIXO TEM COMO FUNÇÃO MOSTRAR QUAIS SÃO OS HOSPITAIS QUE UTILIZAM O MODELO DE AMBULANCIA FIAT , QUAL A PLACA REGISTRADA EM CADA UM E ORDENAR POR MARCA DA AMBULANCIA.
SELECT E.NM_HOSPITAL as "Nome Hospital", A.DS_MARCA_AMBULANCIA as "Marca", A.DS_PLACA_AMBULANCIA AS "Placa"
    FROM T_HS_HOSPITAL E LEFT OUTER JOIN T_HS_AMBULANCIA A
    ON (E.CD_HOSPITAL = A.CD_AMBULANCIA)
    WHERE A.DS_MARCA_AMBULANCIA = 'FIAT'
ORDER BY E.NM_HOSPITAL ASC;

-- NO SELECT ABAIXO TEM COMO FUNÇÃO MOSTRAR QUAIS SÃO AS MARCAS DE AMBULANCIA QUE OS HOSPITAIS OFERECEM, OS NOME DOS HOSPITAIS E ORDENAR POR MARCA DA AMBULANCIA .
SELECT E.NM_HOSPITAL AS "Nome Hospital", A.DS_MARCA_AMBULANCIA AS "Veículos"
    FROM T_HS_HOSPITAL E LEFT OUTER JOIN T_HS_AMBULANCIA A
    ON (E.CD_HOSPITAL = A.CD_AMBULANCIA)
ORDER BY  A.DS_MARCA_AMBULANCIA;

-- NO SELECT ABAIXO TEM COMO FUNÇÃO MOSTRAR A QUANTIDADE DE AMBULANCIA QUE CADA HOSPITAL TEM E ORDENAR POR NOME DO HOSPITAL.
SELECT E.NM_HOSPITAL AS "Nome Hospital", COUNT(A.CD_AMBULANCIA) AS "Quantidade de veiculo"
    FROM T_HS_HOSPITAL E LEFT OUTER JOIN T_HS_AMBULANCIA A
    ON (E.CD_HOSPITAL = A.CD_AMBULANCIA)
    GROUP BY E.NM_HOSPITAL
    HAVING COUNT(A.CD_AMBULANCIA) = 1
ORDER BY E.NM_HOSPITAL ASC;